[workspace]
members = [
    "multidustrycore",
    "apiserver",
    "proxy",
    "gameserver",
    "monolith",
    "labs/quic", "labs/raft", "multidustry-transport", "multidustry-macro", "multidustrycli", "multidustry-kv",
]
resolver = "3"
