[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
reqwest = {version = "0.12.23", default-features = false, features = ["http2", "rustls-tls"]}
tokio = { version = "1.47.1", features = ["full"] }
